/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.odev_2416501012_p;

import static com.mycompany.odev_2416501012_p.NewJFrame.logY;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Tarık
 */
public class SifreEkrani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SifreEkrani.class.getName());
        public static String sifreY="C:\\P2Oyun\\TXTDosyalar\\sifre.txt";
        public static String kelimelerY="C:\\P2Oyun\\TXTDosyalar\\kelimeler.txt";
        public static String logY="C:\\P2Oyun\\TXTDosyalar\\log.txt";
        public static String oyunlarY="C:\\P2Oyun\\TXTDosyalar\\oyunlar.txt";
        
        
        public int hataliSifre=0;
        
         public static void logYaz(String etiket) {
        try (PrintWriter pw = new PrintWriter(new FileWriter(logY, true))) {
            LocalDateTime simdi = LocalDateTime.now();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            pw.println("[" + simdi.format(format) + "] - " + etiket);
        } catch (IOException e) {
            System.err.println("Log yazma hatası: " + e.getMessage());
        }
    }
        
    /**
     * Creates new form SifreEkrani
     */
    public SifreEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Şifre Giriniz :");

        txtSifre.setText("jPasswordField1");

        jButton1.setText("Onayla");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Sayaç : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1)))
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                        
    String girilenSifre = new String(txtSifre.getPassword());
    java.io.File fileSifre = new java.io.File(sifreY);

    // Madde 3: Eğer önceden şifre belirlenmediyse/dosya yoksa ilk kez şifre belirleme
    if (!fileSifre.exists() || fileSifre.length() == 0) {
        String yeniSifre = javax.swing.JOptionPane.showInputDialog(this, 
            "Sistemde kayıtlı şifre bulunamadı.\nLütfen yeni bir şifre belirleyin:", 
            "Şifre Belirleme", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        if (yeniSifre == null || yeniSifre.trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Şifre girmediniz. Program sonlandırılıyor.");
            System.exit(0);
        }

        try (java.io.PrintWriter pw = new java.io.PrintWriter(new java.io.FileWriter(fileSifre))) {
            pw.print(yeniSifre.trim());
            logYaz("Şifre İlk Kez Belirlendi.");
            javax.swing.JOptionPane.showMessageDialog(this, "Şifre başarıyla kaydedildi! Şimdi giriş yapabilirsiniz.");
            txtSifre.setText("");
            return;
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Şifre kaydedilemedi: " + e.getMessage());
            System.exit(0);
        }
    }

    // Madde 4: Şifre zaten varsa dosyadaki şifre ile kontrol et
    try {
        java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(fileSifre));
        String gercekSifre = br.readLine();
        br.close();

        if (gercekSifre != null && girilenSifre.equals(gercekSifre.trim())) {
            // BAŞARILI GİRİŞ
            logYaz("BAŞARILI GİRİŞ: Kullanıcı sisteme giriş yaptı.");
            
            this.dispose(); // Şifre ekranını kapat
            
            // TODO: İkinci adımda oluşturacağımız Ana Oyun Ekranını buradan çağıracağız:
            // new AnaOyunEkrani().setVisible(true);
            javax.swing.JOptionPane.showMessageDialog(null, "Giriş Başarılı! Oyun Açılıyor...");
            
        } else {
            // HATALI GİRİŞ
            hataliSifre++;
            logYaz("HATALI GİRİŞ DENEMESİ: Deneme No: " + hataliSifre);

            if (hataliSifre >= 3) {
                // Madde 4: 3 sefer hatalı girilirse program sonlanacak
                logYaz("PROGRAM ENGELLENDİ: 3 Hatalı giriş nedeniyle program sonlandırıldı.");
                javax.swing.JOptionPane.showMessageDialog(this, "3 defa hatalı şifre girdiniz! Program kapatılıyor.");
                System.exit(0);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Hatalı şifre! Kalan hakkınız: " + (3 - hataliSifre));
                txtSifre.setText("");
                txtSifre.requestFocus();
            }
        }
    } catch (java.io.IOException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Şifre dosyası okunurken hata: " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SifreEkrani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
